spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/qe_v2_db
    username: ${POSTGRES_USER:-admin}
    password: ${POSTGRES_PASSWORD:-admin}

jwt:
  secret: ${JWT_SECRET:-OMGItsQuestEngineV2JWTSuperSecureTokenMadeByDN}
  expiration: 86400000

admin:
  reset:
    secret: ${ADMIN_RESET_SECRET:-change-me-in-production}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
